# Generated by Django 3.1.4 on 2020-12-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201231_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_accessories',
            options={'verbose_name': 'ProductAccessory', 'verbose_name_plural': 'Product Accessories'},
        ),
        migrations.AddField(
            model_name='product_accessories',
            name='PACAccessories',
            field=models.ManyToManyField(related_name='Accessories_Product', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product_accessories',
            name='PACProduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_Product', to='product.product'),
            preserve_default=False,
        ),
    ]
