# Generated by Django 3.1.4 on 2020-12-31 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201231_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACAccessories',
            field=models.ManyToManyField(related_name='Accessories_Product', to='product.Product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_Product', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product_alternatives',
            name='PALNAlternative',
            field=models.ManyToManyField(related_name='Alternatives_Product', to='product.Product', verbose_name='Alternative'),
        ),
        migrations.AlterField(
            model_name='product_alternatives',
            name='PALNProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Product', to='product.product', verbose_name='Product'),
        ),
    ]
