# Generated by Django 3.1.4 on 2021-01-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210112_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDCost',
            new_name='PRDcost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDCreated',
            new_name='PRDcreated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDName',
            new_name='PRDname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDPrice',
            new_name='PRDprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDDiscountPrice',
        ),
    ]
