# Generated by Django 3.1.4 on 2021-01-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_prddiscountprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDname',
            new_name='PRDName',
        ),
    ]
