# Generated by Django 3.1.4 on 2021-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210112_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIsBestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDIsNew',
            field=models.BooleanField(default=True),
        ),
    ]
